### ISSUE TITLE
error while executing ransac.py

### ISSUE THREAD

**Issue by KingAlawaka** [vishwa91/pyimreg#4]
in my this directory i already include the sift file but couldnt run. I am using ubuntu.. because of sift exe do i have to use windows? Thanks in advance 
``sh: 1: ./sift: not found
processed temp/1.pgm
sh: 1: ./sift: not found
processed temp/2.pgm
Traceback (most recent call last):
  File "ransac.py", line 162, in <module>
    key1 = read_features_from_file('temp/1.key')
  File "/home/king/opencv_codes/pyimreg/sift.py", line 34, in read_features_from_file
    num = int(header[0]) #the number of features
IndexError: list index out of range``

**Comment by vishwa91** [comment]
Since you are in Ubuntu, you need 'sift', and not 'sift.exe'. Also, 'sift' will need read permissions. You can do the following in the same directory as sift at the prompt:
$ chmod sift 755

That should take care.
